### ISSUE TITLE
Shopkeep analogy

### ISSUE THREAD

**Issue by contolini** [ascott1/ethical-web-dev#13]
From the [intro](https://github.com/ascott1/ethical-web-dev/blob/master/web-apps-for-everyone/01-title-intro.md):

> Or worse, the site will silently fail, akin to the shopkeeper refusing to open the till and take payment.

This implies that the developer could easily flip a switch (open a cash register) to get their product to work in older browsers, but s/he has arrogantly chosen not to. It's more often the case that the developer is too lazy to do the research to get it to work. Something like, "akin to the shopkeeper ignoring a customer because they're not worthy of the owner's time" might work better.

**Comment by ascott1** [comment]
Yeah, this analogy always felt a little flimsy (and maybe even preachy). Your suggestion definitely makes itbetter... should I just kill it off entirely or does it support the point?

**Comment by contolini** [comment]
I dig the analogy. Most websites are looking to attract and retain visitors, much the same as stores to customers.
