### ISSUE TITLE
User needs

### ISSUE THREAD

**Issue by contolini** [ascott1/ethical-web-dev#15]
https://github.com/ascott1/ethical-web-dev/blob/master/web-apps-for-everyone/02-progressive-enhancement.md

> Progressive enhancement is about defining what a user _needs_ and ensuring that it is always delivered to them, in a way that will work regardless of network conditions, device, or browser.

The "needs" part is a little ambiguous. Maybe change it to something like:

> Progressive enhancement is about defining what a user _needs_ to get from your website and ensuring that it is always delivered to them, in a way that will work regardless of network conditions, device, or browser.

**Comment by ascott1** [comment]
Much clearer.
