### ISSUE TITLE
Progressive enhancement is still relevant

### ISSUE THREAD

**Issue by contolini** [ascott1/ethical-web-dev#16]
I would change the subtitle from "[Is progressive enhancement still relevant?](https://github.com/ascott1/ethical-web-dev/blob/master/web-apps-for-everyone/02-progressive-enhancement.md#is-progressive-enhancement-still-relevant)" to "Progressive enhancement is still relevant". It felt odd to read about the importance of progressive enhancement and then read a huge headline casting doubt on it relevancy.

**Comment by ascott1** [comment]
:+1:  Good suggestion!
