### ISSUE TITLE
JS blocking test

### ISSUE THREAD

**Issue by contolini** [ascott1/ethical-web-dev#17]
You should link to the code that will let people [run their own experiment](https://github.com/ascott1/ethical-web-dev/blob/master/web-apps-for-everyone/02-progressive-enhancement.md#run-your-own-experiment).

It looks like it's [here](https://github.com/alphagov/frontend/pull/452/files). Bonus points if you turn it into a little JS snippet that people can drop into their sites.

**Comment by ascott1** [comment]
Brilliant.

**Comment by ascott1** [comment]
Here's what the code looks like adapted to just HTML and un-minified:

``` html
<img src="base-js.gif" alt="" role="presentation"
  style="position: absolute; left: -9999em; height: 0px; width: 0px;">
<script type="text/javascript">
  (function(){
    var a = document.createElement("img");
    a.src = "with-js.gif";
    a.alt = "";
    a.role = "presentation";
    a.style.position = "absolute";
    a.style.left = "-9999em";
    a.style.height = "0px";
    a.style.width = "0px";
    document.getElementById("wrapper").appendChild(a);
  })();
</script>
 <noscript>
   <img src="without-js.gif" alt="" role="presentation"
    style="position: absolute; left: -9999em; height: 0px; width: 0px;">
 </noscript>

```

**Comment by contolini** [comment]
:+1:

It occurs to me that this example is a recommendation to use [web beacons](https://en.wikipedia.org/wiki/Web_beacon) which have some privacy implications that you'll probably discuss in a subsequent book. You might want to add a sentence about that.

**Comment by ascott1** [comment]
Good thought. I added a little note:

> This approach, used by gov.uk, is a recommendation to use web beacons which may have some privacy implications. Web beacons are typically hidden pieces of content used to check if a user has accessed a piece of content and are common in email marketing campaigns. Privacy issues such as this will be discussed in an upcoming title in the series.
