### ISSUE TITLE
Auto loan calculator

### ISSUE THREAD

**Issue by contolini** [ascott1/ethical-web-dev#18]
You mention Scott starting the progressively-enhanced [auto loan calculator](https://github.com/ascott1/ethical-web-dev/blob/master/web-apps-for-everyone/02-progressive-enhancement.md#how-can-we-approach-progressive-enhancement-today). Has he made any progress on it? What progressive enhancement strategy did he choose? Can the code be viewed anywhere on GitHub? It might serve as a nice hands-on example.

**Comment by ascott1** [comment]
Sadly, I _think_ it was just discussed and has not yet been built. I'll double check, but I like the idea of this as a hands on example.
