### ISSUE TITLE
Explain IIFE

### ISSUE THREAD

**Issue by contolini** [ascott1/ethical-web-dev#19]
Non-JS folks may wonder what all the weird parens are doing in the [following example](https://github.com/ascott1/ethical-web-dev/blob/master/web-apps-for-everyone/02-progressive-enhancement.md#how-can-we-approach-progressive-enhancement-today):

``` js
(function() {
  if (!('visibilityState' in document)) {
    return false;
  }

  // rest of your code
}());
```

Might be worth adding a footnote explaining that the [IIFE](http://benalman.com/news/2010/11/immediately-invoked-function-expression/) is unrelated to the `visibilityState` check.

**Comment by ascott1** [comment]
Makes sense. I added the following as what will appear as a "note" in the final version of the book:

> Note: The example above is wrapped in an Immediately-Invoked Function Expression (IIFE), which may look a bit odd if you're not a JavaScript developer. This ensures that the code executes immediately while avoiding the pollution of the global scope. If you are interested in learning more Ben Alman has written a very detailed [post about IIFEs](http://benalman.com/news/2010/11/immediately-invoked-function-expression/).

**Comment by contolini** [comment]
:+1:
