### ISSUE TITLE
Multi-sensory

### ISSUE THREAD

**Issue by contolini** [ascott1/ethical-web-dev#23]
https://github.com/ascott1/ethical-web-dev/blob/master/web-apps-for-everyone/03-accessibility.md#wcag-20

> A link that is only a different color from the text would be imperceptible to a color blind users. Instead, we should be sure to alter the color as well as provide an underline to the link. This provides a multi sensory option to the user.

Is it multi sensory? Isn't it still just one sense: sight?

**Comment by ascott1** [comment]
Agreed. multi sensory is the wrong word here.

**Comment by ascott1** [comment]
I updated this and also added a footnote about color blindness:

One common use case of perception is providing written transcripts of audio material or captioning video material. Perhaps a less obvious example is the style of links across the web. A link that is only a different color from the text would be imperceptible to a color blind users[^1]. Instead, we should be sure to alter the color as well as provide an underline to the link. This provides a perceptible option to the color blind user.

..IMG...

[^1]: Color blindess affects a significant portion of the population, specifically those born male. Roughly 8% of male born people are said to have some form of color blindness. https://en.wikipedia.org/wiki/Color_blindness#Epidemiology
