### ISSUE TITLE
Outline screenshots

### ISSUE THREAD

**Issue by contolini** [ascott1/ethical-web-dev#25]
It depends on the medium, of course, but you might want to add an outline to the [Google screenshots](https://github.com/ascott1/ethical-web-dev/blob/master/web-apps-for-everyone/04-inclusive-forms.md#inclusive-gender) so they don't disappear into a white background.

**Comment by ascott1** [comment]
O'Reilly's publishing system has it's own styles/formatting. I'm going to hold off on this to see how it renders in print there.
