### ISSUE TITLE
Hyperlink

### ISSUE THREAD

**Issue by contolini** [ascott1/ethical-web-dev#27]
> This makes the humble link one of the most powerful aspects of the web.

I'd use "hyperlink" here to be 100% sure the reader knows what you're talking about. You also get a fun alliteration out of it: "humble hyperlink." Later uses of the term are fine as just "link."

https://github.com/ascott1/ethical-web-dev/blob/master/web-apps-that-work-everywhere/02-url.md#url-design

**Comment by ascott1** [comment]
Love it.
