### ISSUE TITLE
Sharable

### ISSUE THREAD

**Issue by contolini** [ascott1/ethical-web-dev#28]
TIL "sharable" is [valid spelling](http://grammarist.com/spelling/sharable-shareable/). It looks weird to me, though, and I'm much more used to "shareable." Just my two cents.

https://github.com/ascott1/ethical-web-dev/blob/master/web-apps-that-work-everywhere/02-url.md#sharable-urls

**Comment by ascott1** [comment]
👍  on second look, I agree. My spelling is 🇺🇸  through and through, I guess.
