### ISSUE TITLE
Pretty links are now the default in WordPress

### ISSUE THREAD

**Issue by contolini** [ascott1/ethical-web-dev#29]
As of v4.2, [pretty permalinks are on by default](https://wptavern.com/wordpress-4-2-will-automatically-enable-pretty-permalinks-for-new-sites-on-installation) _if the server supports it_. I'm guessing most servers do support it nowadays so you'll want to change "...the default WordPress permalink structure produces URLs such as..." to something like "...many WordPress websites produce URLs such as...".

https://github.com/ascott1/ethical-web-dev/blob/master/web-apps-that-work-everywhere/02-url.md#keep-urls-simple

**Comment by ascott1** [comment]
Oh, that's awesome (and shows how out of the WordPress game I am). I changed this whole section around a bit:

### Keep URLs simple

Effective URLs are simple, short, and human-friendly. This makes them easier to type and remember for users.

WordPress is the most popular content manager for the web and powers over 25%[^1](https://w3techs.com/technologies/history_overview/content_management/all/y) percent of websites. Unfortunately, until relatively recently[^2](https://core.trac.wordpress.org/changeset/31089), the default WordPress [permalink structure](https://codex.wordpress.org/Introduction_to_Blogging#Pretty_Permalinks) produced URLs such as:

```
/index.php?p=423
```

To a user this URL format is seemingly random and arbitrary. Fortunately, WordPress allowed users to create “pretty” permalink structure, and as of 2015, now does this by default. The pretty permalink structure can be descriptive and clean, such as:

```
/posts/effective-altruism/
```

WordPress core contributor Eric Lewis [reportedly commented on the change](https://wptavern.com/wordpress-4-2-will-automatically-enable-pretty-permalinks-for-new-sites-on-installation) saying ““Delivering pretty permalinks by default seems in line with a bunch of core philosophies – great out-of-the-box, design for the majority, simplicity, clean, lean and mean.”

By creating link structures that are simple and human readable, we are able to provide our users with a clear description of a URL’s content.
