### ISSUE TITLE
Screen resolutions

### ISSUE THREAD

**Issue by contolini** [ascott1/ethical-web-dev#31]
> Today, the number of devices that connect to the web is again expanding.

I'd replace "again" with "rapidly" because you then go on to state there are 119 different screen resolutions compared to the handful that existed in the early web.

https://github.com/ascott1/ethical-web-dev/blob/master/web-apps-that-work-everywhere/03-responsive-design.md#responsive-design

**Comment by ascott1** [comment]
👍
