### ISSUE TITLE
Media query overlap

### ISSUE THREAD

**Issue by contolini** [ascott1/ethical-web-dev#32]
```
@media (max-width: 600px) {
  /* Smaller device/browser styles */
}

@media (min-width: 600px) {
  /* Large device/browser styles */
}
```

A 600px wide screen will trigger both media queries. Bump `min-width: 600px` to `min-width: 601px` (or `max-width: 599px`).

https://github.com/ascott1/ethical-web-dev/blob/master/web-apps-that-work-everywhere/03-responsive-design.md#process

**Comment by ascott1** [comment]
Math!
