### ISSUE TITLE
Four Pre's

### ISSUE THREAD

**Issue by contolini** [ascott1/ethical-web-dev#33]
The four pre's section is a little confusing to me. It comes right after you discuss how important it is reduce the number of resources the user has to download. Doesn't pre-fetching content increase the amount of stuff the user is downloading? The `prerender` technique looks incredibly powerful, and I'm excited to use it, but isn't forcing the user to download an entire second page of content a performance nightmare? I can see some overzealous developers using it as a way to make subsequent pages load quickly at the risk of users wasting MBs of bandwidth if they never decide to click over to page #2.

I think this section needs some sort of "with great power comes great responsibility" disclaimer. I'd also consider moving it toward the end of the chapter because it feels much more cutting-edge and advanced than JS minification, responsive images, gzipping, etc.

https://github.com/ascott1/ethical-web-dev/blob/master/web-apps-that-work-everywhere/04-web-performance.md#the-four-pres-prefetch-preconnect-prerender-preload

**Comment by ascott1** [comment]
This is a great point. I think it's really interesting technology, and has some really valid use cases, but maybe conflicts with other advice in the book. I'll play around with this and see if there's a way to fit it in to the book, otherwise it may just get chopped.

**Comment by ascott1** [comment]
After reading through this section, I opted to cut it. It _is_ interesting, but really felt forced and out of place.
