### ISSUE TITLE
GitHub linking

### ISSUE THREAD

**Issue by contolini** [ascott1/ethical-web-dev#36]
When linking to GitHub files it's a good idea to link directly to a commit (doesn't matter which one), otherwise the lines you permalink to will be incorrect when the file is inevitably changed. Or if the file is moved or deleted down the road, it'll 404.

For example, do `https://github.com/h5bp/server-configs-apache/blob/58d58408821f3ade93cae09cd33fdfa4b376d533/dist/.htaccess#L740-L774` instead of `https://github.com/h5bp/server-configs-apache/blob/master/dist/.htaccess#L740-L774`.

https://github.com/ascott1/ethical-web-dev/blob/master/web-apps-that-work-everywhere/04-web-performance.md#gzip

**Comment by ascott1** [comment]
This is smart, especially in a book that mentions URL permanence.
