### ISSUE TITLE
Rails config.assets.digest ?

### ISSUE THREAD

**Issue by contolini** [ascott1/ethical-web-dev#37]
`Rails config.assets.digest` is a broken link, not sure what it's supposed to point to.

https://github.com/ascott1/ethical-web-dev/blob/master/web-apps-that-work-everywhere/04-web-performance.md#caching

**Comment by ascott1** [comment]
I love that the URL I have here is `what-is-fingerprinting-and-why-should-i-care`. I'm trying to remember what that was from.

**Comment by ascott1** [comment]
Ha! That's actually the header of the Rails docs http://guides.rubyonrails.org/asset_pipeline.html#what-is-fingerprinting-and-why-should-i-care-questionmark
