### ISSUE TITLE
`html` variable

### ISSUE THREAD

**Issue by contolini** [ascott1/ethical-web-dev#38]
```
// we can set a class on the html el when fonts are loading
html.classList.add('font-loading');
```

I'd indicate that `html` is defined outside this code snippet:

```
// `html` is an object reference to the page's <html> element
// we can give it a class indicating fonts are loading
html.classList.add('font-loading');
```

https://github.com/ascott1/ethical-web-dev/blob/master/web-apps-that-work-everywhere/04-web-performance.md#optimizing-web-fonts

**Comment by ascott1** [comment]
I'm going to add the line to assign the variable. That was probably an oversight on my part when copying from my demo:

```
// we can set a class on the html el when fonts are loading
var html = document.documentElement;
html.classList.add('font-loading');
```
